apiVersion: v2
name: coturn
type: application
description: A Helm chart to deploy coturn
home: "https://github.com/jessebot/coturn-chart"
version: 4.1.3

# renovate: image=coturn/coturn
appVersion: 4.6.2
sources:
  - "https://github.com/jessebot/coturn-chart"

maintainers:
  - name: "jessebot"
    email: "jessebot@linux.com"
    url: "https://github.com/jessebot/"

dependencies:
  - name: postgresql
    version: 12.7.3
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
