apiVersion: v2
name: coturn
type: application
description: A Helm chart to deploy coturn
home: "https://github.com/small-hack/coturn-chart"
version: 5.2.0

# renovate: image=coturn/coturn
appVersion: 4.6.2
sources:
  - "https://github.com/small-hack/coturn-chart"

maintainers:
  - name: "jessebot"
    email: "jessebot@linux.com"
    url: "https://github.com/jessebot/"

dependencies:
  - name: postgresql
    version: 15.2.8
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: mysql
    version: 10.1.1
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mysql.enabled
